name: lumu_evolve
description: A premium, enterprise-grade utility package evolving Dart with fluent scope functions, conditional selectors, and powerful type helpers.
version: 1.1.2
homepage: https://github.com/lumunar/lumu_evolve
repository: https://github.com/lumunar/lumu_evolve
issue_tracker: https://github.com/lumunar/lumu_evolve/issues

topics:
  - extensions
  - utilities
  - kotlin
  - fluent-api

environment:
  sdk: '>=3.12.2 <4.0.0'
  flutter: '>=3.44.4'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0